---
{"kind": "pipeline", "type": "docker", "name": "testing", "platform": {"os": "linux", "arch": "amd64"}, "steps": [{"name": "vet", "image": "golang:1.12", "pull": "always", "commands": ["go vet ./..."], "volumes": [{"name": "gopath", "path": "/go"}]}, {"name": "test", "image": "golang:1.12", "pull": "always", "commands": ["go test -cover ./..."], "volumes": [{"name": "gopath", "path": "/go"}]}], "volumes": [{"name": "gopath", "temp": {}}], "trigger": {"ref": ["refs/heads/master", "refs/tags/**", "refs/pull/**"]}}
---
{
  "kind": "pipeline",
  "type": "docker",
  "name": "linux-amd64",
  "platform": {
    "os": "linux",
    "arch": "amd64"
  },
  "steps": [
    {
      "name": "build-push",
      "image": "golang:1.12",
      "pull": "always",
      "environment": {
        "CGO_ENABLED": "0"
      },
      "commands": [
        "go build -v -ldflags \"-X main.version=${DRONE_COMMIT_SHA:0:8}\" -a -tags netgo -o release/linux/amd64/drone-ansible"
      ],
      "when": {
        "event": {
          "exclude": [
            "tag"
          ]
        }
      }
    },
    {
      "name": "build-tag",
      "image": "golang:1.12",
      "pull": "always",
      "environment": {
        "CGO_ENABLED": "0"
      },
      "commands": [
        "go build -v -ldflags \"-X main.version=${DRONE_TAG##v}\" -a -tags netgo -o release/linux/amd64/drone-ansible"
      ],
      "when": {
        "event": [
          "tag"
        ]
      }
    },
    {
      "name": "executable",
      "image": "golang:1.12",
      "pull": "always",
      "commands": [
        "./release/linux/amd64/drone-ansible --help"
      ]
    },
    {
      "name": "dryrun",
      "image": "plugins/docker",
      "pull": "always",
      "settings": {
        "dry_run": true,
        "tags": "linux-amd64",
        "dockerfile": "docker/Dockerfile.linux.amd64",
        "repo": "864091978270.dkr.ecr.ap-southeast-2.amazonaws.com/plugins/ansible"
      },
      "when": {
        "event": [
          "pull_request"
        ]
      }
    },
    {
      "name": "publish",
      "image": "plugins/docker",
      "pull": "always",
      "settings": {
        "auto_tag": true,
        "auto_tag_suffix": "linux-amd64",
        "dockerfile": "docker/Dockerfile.linux.amd64",
        "repo": "864091978270.dkr.ecr.ap-southeast-2.amazonaws.com/plugins/ansible"
      },
      "when": {
        "event": {
          "exclude": [
            "pull_request"
          ]
        }
      }
    }
  ],
  "depends_on": [
    "testing"
  ],
  "trigger": {
    "ref": [
      "refs/heads/master",
      "refs/tags/**",
      "refs/pull/**"
    ]
  }
}
